sudo: false
language: rust
matrix:
  include:
    - rust: nightly
    - rust: beta
    - rust: stable
      env: # Drop this once stable >= 1.15!
        - NOSERDE=1
script:
  - cargo build
  - cargo test
  - ([ "$NOSERDE" == 1 ] || cargo build --features use_serde)
  - ([ "$NOSERDE" == 1 ] || cargo test --features use_serde)
