sudo: false
language: rust
matrix:
  include:
    - rust: nightly
    - rust: beta
    - rust: stable
script:
  - cargo build
  - cargo test
  - cargo build --features use_serde
  - cargo test --features use_serde
