[package]
name = "string-wrapper"
version = "0.1.6"
authors = ["Christopher Armstrong <radix@twistedmatrix.com>"]
license = "MIT / Apache-2.0"
repository = "https://github.com/radix/string-wrapper"
description = "A possibly-stack-allocated string with generic bytes storage"

[lib]
path = "lib.rs"
doctest = false

[features]
use_serde = ["serde", "serde_derive"]

[dev-dependencies]
serde_json = "0.8"

[dependencies]
serde = {version = "0.8", optional = true}
serde_derive = {version = "0.8", optional = true}
